[project]
name = "trashbar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "playsound==1.2.2",
    "pyinstaller>=6.21.0",
    "pyqt6>=6.11.0",
    "pyside6>=6.11.1",
    "pywin32>=312",
    "send2trash>=2.1.0",
    "trash-cli>=0.24.5.26",
    "winshell>=0.6",
]
